version: "3.9"
services:
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'sigeie_db'
      MYSQL_ROOT_PASSWORD: 'root'
    container_name: sigeie_mysql_db
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  redis:
    image: redis:7.2
    restart: always
    container_name: sigeie_redis_db
    ports:
      - "6379:6379"
