version: "3.9"
services:
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_DATABASE: 'sigeie_db'
      MYSQL_ROOT_PASSWORD: 'root'
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/db:/var/lib/mysql
